server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: "api-gateway"
logging:
  level:
    web: info
    root: info

microservices:
  jwt:
    secret: ${JWT_SECRET:jwtsecretunivantokenkeygenerator}
  univan:
    url: ${UNIVAN_URL:http://localhost:5000}
  carpool:
    url: ${CARPOOL_URL:http://localhost:5001}
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}
  routes:
    url: ${ROUTES_URL:http://localhost:5004}
  history:
    url: ${HISTORY_URL:http://localhost:5003}